package example.com.zztest.Bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import example.com.zztest.Bean.ArticleBean;

import example.com.zztest.Bean.ArticleBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articleBeanDaoConfig;

    private final ArticleBeanDao articleBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articleBeanDaoConfig = daoConfigMap.get(ArticleBeanDao.class).clone();
        articleBeanDaoConfig.initIdentityScope(type);

        articleBeanDao = new ArticleBeanDao(articleBeanDaoConfig, this);

        registerDao(ArticleBean.class, articleBeanDao);
    }
    
    public void clear() {
        articleBeanDaoConfig.getIdentityScope().clear();
    }

    public ArticleBeanDao getArticleBeanDao() {
        return articleBeanDao;
    }

}
